
PLAY [kds-data-closeEdit] ****************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************
ok: [10.11.5.73]

TASK [all : Stop "kds-data-closeEdit" service] *******************************************************************************************************************************************************************************************************************************
changed: [10.11.5.73]

TASK [all : Copy "kds-data-closeEdit" Package To Target-Hosts] ***************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.73]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data-closeEdit_release/v1.19.3.RELEASE/kds-data-closeEdit.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
10.11.5.73                 : ok=2    changed=1    unreachable=0    failed=1   

[Finish] Failed to start  [1324]