kds-data-commitEdit
Traceback (most recent call last):
  File "/home/op/mesh_deploy_5.80/no_cat_release.py", line 83, in <module>
    with open('/home/op/mesh_deploy_5.80/%s' %server_name) as f:
IOError: [Errno 2] No such file or directory: '/home/op/mesh_deploy_5.80/kds-data-commitEdit'
[Finish] Failed to deploy [393]