Traceback (most recent call last):
  File "/home/op/mesh_deploy_5.80/no_cat_release.py", line 78, in <module>
    release_pathold = sys.argv[1]
IndexError: list index out of range
[Finish] Failed to deploy [454]