2018-11-27 13:42:30,827 INFO 60801[guizhou_start.py:18 start_cmd]: --------------------------------------------------------------------------------------------
2018-11-27 13:42:30,827 INFO 60801[guizhou_start.py:19 start_cmd]: now start the host : 10.11.5.79
2018-11-27 13:42:30,839 INFO 60801[transport.py:1746 _log]: Connected (version 2.0, client OpenSSH_7.2p2)
2018-11-27 13:42:30,925 INFO 60801[transport.py:1746 _log]: Authentication (publickey) failed.
2018-11-27 13:42:30,943 INFO 60801[transport.py:1746 _log]: Authentication (password) successful!
2018-11-27 13:42:31,268 INFO 60801[guizhou_start.py:25 start_cmd]: cmd is : sudo /data/CI/kds-meta_30_13200/kds-meta.sh start
2018-11-27 13:42:31,269 INFO 60801[guizhou_start.py:26 start_cmd]: error list start is :[]
2018-11-27 13:42:31,269 INFO 60801[guizhou_start.py:27 start_cmd]: stdout list start is :[u'/data/CI/kds-meta_30_13200\n', u'kds-meta.jar\n']
2018-11-27 13:42:31,270 INFO 60801[guizhou_start.py:28 start_cmd]: process is starting,wait a momunt
2018-11-27 13:42:31,270 INFO 60801[guizhou_start.py:18 start_cmd]: --------------------------------------------------------------------------------------------
2018-11-27 13:42:31,270 INFO 60801[guizhou_start.py:19 start_cmd]: now start the host : 10.11.5.80
2018-11-27 13:42:31,278 INFO 60801[transport.py:1746 _log]: Connected (version 2.0, client OpenSSH_7.2p2)
2018-11-27 13:42:31,364 INFO 60801[transport.py:1746 _log]: Authentication (publickey) successful!
2018-11-27 13:42:31,655 INFO 60801[guizhou_start.py:25 start_cmd]: cmd is : sudo /data/CI/kds-meta_30_13200/kds-meta.sh start
2018-11-27 13:42:31,656 INFO 60801[guizhou_start.py:26 start_cmd]: error list start is :[]
2018-11-27 13:42:31,656 INFO 60801[guizhou_start.py:27 start_cmd]: stdout list start is :[u'/data/CI/kds-meta_30_13200\n', u'kds-meta.jar\n']
2018-11-27 13:42:31,656 INFO 60801[guizhou_start.py:28 start_cmd]: process is starting,wait a momunt
2018-11-27 13:42:31,656 INFO 60801[guizhou_start.py:18 start_cmd]: --------------------------------------------------------------------------------------------
2018-11-27 13:42:31,656 INFO 60801[guizhou_start.py:19 start_cmd]: now start the host : 10.11.5.81
2018-11-27 13:42:31,668 INFO 60801[transport.py:1746 _log]: Connected (version 2.0, client OpenSSH_7.2p2)
2018-11-27 13:42:31,757 INFO 60801[transport.py:1746 _log]: Authentication (publickey) failed.
2018-11-27 13:42:31,780 INFO 60801[transport.py:1746 _log]: Authentication (password) successful!
2018-11-27 13:42:32,116 INFO 60801[guizhou_start.py:25 start_cmd]: cmd is : sudo /data/CI/kds-meta_30_13200/kds-meta.sh start
2018-11-27 13:42:32,117 INFO 60801[guizhou_start.py:26 start_cmd]: error list start is :[]
2018-11-27 13:42:32,117 INFO 60801[guizhou_start.py:27 start_cmd]: stdout list start is :[u'/data/CI/kds-meta_30_13200\n', u'kds-meta.jar\n']
2018-11-27 13:42:32,117 INFO 60801[guizhou_start.py:28 start_cmd]: process is starting,wait a momunt
Traceback (most recent call last):
  File "/home/op/mesh_deploy_5.80/guizhou_start.py", line 32, in <module>
    ip , krs_sh, krs_jar, krs_jar_bak, lib_path ,server  = line.strip().split()
ValueError: need more than 0 values to unpack
[Finish] Failed to deploy [592]