
PLAY [kds-data] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************************
ok: [10.11.5.77]
ok: [10.11.5.37]
ok: [10.11.5.74]
ok: [10.11.5.36]
ok: [10.11.5.38]
ok: [10.11.5.73]
ok: [10.11.5.75]
ok: [10.11.5.76]
ok: [10.11.5.35]
ok: [10.11.5.78]
ok: [10.11.5.79]
ok: [10.11.5.81]
ok: [10.11.5.85]
ok: [10.11.5.86]

TASK [kds-data : Copy "kds-data" Package To Target-Hosts] *******************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.35]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.37]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.38]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.73]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.74]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.75]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.36]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.76]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.78]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.77]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.79]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.81]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.85]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [10.11.5.86]: FAILED! => {"changed": false, "msg": "Could not find or access '/mnt/data1/release-data/kds-data_release/v.RELEASE/kds-data.jar' on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
	to retry, use: --limit @/home/op/Java_service_release/Java_service_release.retry

PLAY RECAP ******************************************************************************************************************************************************************************************************
10.11.5.35                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.36                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.37                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.38                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.73                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.74                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.75                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.76                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.77                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.78                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.79                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.81                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.85                 : ok=1    changed=0    unreachable=0    failed=1   
10.11.5.86                 : ok=1    changed=0    unreachable=0    failed=1   

[Finish] Failed to start  [870]